### NumPy Lab

Holden Davis

In [75]:
import numpy as np

### <span style="color:red">Task 1</span>

Use the appropriate NumPy methods to do the following: Fill a 2-by-3 arrayay with ones, a 3-by-3 arrayay with zeros and a 2-by-5 arrayay with 5s. Display each arrayay.

In [76]:
a = np.ndarray(shape=(2,3))
a.fill(1)

b = np.ndarray(shape=(3,3))
b.fill(0)

c = np.ndarray(shape=(2,5))
c.fill(5)

print(a)
print()
print(b)
print()
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


### <span style="color:red">Task 2</span>

Use arange to create an arrayay containing the values 1-15, reshape it into a 3 by 5 arrayay, then use indexing and slicing techniques to perform each of the following operations :
* Select and display the 3rd row
* Select and display the 4th column
* Select and display the first and second row.
* Select and display the 2nd column up to and including the 4th column
* Select and display the element that is in the 2nd row and the 4th column
* Select and display all the elements from the 1st and 2nd row and the first column, the 3rd column, and the 5th column.

Remember, rows and columns start indexing at 0.  When asked to display the 2nd row, you should display the row with the index of 1. The same applies to columns.


In [77]:
array = np.arange(1,16).reshape(3,5)
print("3rd row:",array[2])
print()
print("4th column:",array[:, 3])
print()
print("1st and second rows:",array[:, 1:5])
print()
print("2nd column up to and including 4th column:",array[1][3])
print()
print("1st and 2nd rows at 1st, 3rd, and 5th columns:",array[0:2, [0,2,4]])

3rd row: [11 12 13 14 15]

4th column: [ 4  9 14]

1st and second rows: [[ 2  3  4  5]
 [ 7  8  9 10]
 [12 13 14 15]]

2nd column up to and including 4th column: 9

1st and 2nd rows at 1st, 3rd, and 5th columns: [[ 1  3  5]
 [ 6  8 10]]


### <span style="color:red">Task 3</span>

Use arange to create a 2-by-2 arrayay containing the numbers 0–3. Use **broadcasting** to perform each of the following operations on the **original** arrayay :

* Square every element of the arrayay.

* Add 6 to every element of the arrayay.

* Multiply every element of the arrayay by 3.

Make sure you display the results.

In [78]:
array = np.arange(0,4).reshape(2,2)
array **= 2
array += 6
array *= 3
print(array)

[[18 21]
 [30 45]]


### <span style="color:red">Task 4</span> 

Use arange to create a 3-by-3 arrayay containing the even integers from 2 through 18. Use arange to create a second 3-by-3 arrayay containing the integers from 9 down to 1, then multiply the first arrayay by the second.

In [79]:
array = np.arange(2,19, step=2).reshape(3,3)
array2 = np.arange(9, 0, step=-1).reshape(3,3)
print("first:",array)
print()
print("second:",array2)
print()
print("first * second:",array * array2)

first: [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

second: [[9 8 7]
 [6 5 4]
 [3 2 1]]

first * second: [[18 32 42]
 [48 50 48]
 [42 32 18]]


### <span style="color:red">Task 5</span> 
 
Use a list comprehenstion to create a 2-by-3 arrayay containing the first six powers of 2 beginning with 2<sup>0</sup>. Flatten the arrayay first with method ```flatten```, then with ```ravel```. In each case, display the result then display the original arrayay to show that it was unmodified.

<span style ="color:red">Answer this question in markdown: What is the difference between flatten and ravel?

In [80]:
array = np.array([2**i for i in range(6)]).reshape(2,3)
print("original:",array)
print()
print("flatten():",array.flatten())
print()
print("original:",array)
print()
print("ravel():",array.ravel())
print()
print("original:",array)


original: [[ 1  2  4]
 [ 8 16 32]]

flatten(): [ 1  2  4  8 16 32]

original: [[ 1  2  4]
 [ 8 16 32]]

ravel(): [ 1  2  4  8 16 32]

original: [[ 1  2  4]
 [ 8 16 32]]


You can't perceive a difference between ravel and flatten purely off of what I've written, so I had to look this one up to confirm! Flatten will always return a copy of the input array, whereas ravel will attempt to return a view of the original array if possible, creating a copy only if necessary. This ends up being a difference mainly in terms of memory consumption.